development:
  adapter: postgresql
  encoding: utf8
  database: spotcheck_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: spotcheck_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: spotcheck_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST